### PR TITLE
Ignore fix for ubuntu bug #815528 in ubuntu 16.04

### PR DESCRIPTION
**Pull request by alexbel**
It seems that the ubuntu bug has been closed as "invalid" because since 2014 "the init.d script is not shipped in Ubuntu at all" and this fix is obsolete now.
I'm not sure if it's safe to delete the bug fix completely, but at least it wouldn't be broken in ubuntu 16.04.
I tested on ubuntu 16.04.1 LTS and the recipe works fine.

### CODE REVIEW

**Comment by scopenco** [comment]
I'll test in my env and let you know

**Comment by scopenco** [comment]
i think the better way to use 
```
-if node['platform'] == 'ubuntu'
+if node['platform'] == 'ubuntu' && node['platform_version'].to_i < 16
```

i'll update recipe shortly

**Comment by scopenco** [comment]
released 0.1.1

**Comment by alexbel** [comment]
@scopenco Thanks!

**Pull request closed without merging**
